// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class vendorstatusinuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vendorstatusinuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202408010723264_vendor status in user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
